### ISSUE TITLE
Cannot moderate package tinycc

### ISSUE THREAD

**Issue by AnthonyMastrean** [chocolatey/chocolatey.org#177]
I'm can't submit moderation comments (status: submitted) for this package. I've been able to moderate other packages today in the same browser session.

https://chocolatey.org/packages/tinycc/0.9.26

I get the basic error message
> Sorry, an error occurred while processing your request.

In case someone else can get through, my moderation comments:
>Avoid hotlinking package icons:
> 
> https://github.com/chocolatey/choco/wiki/CreatePackages#package-icon-guidelines
> 
> You can use this URL, which meets the current criteria:
> 
> https://cdn.rawgit.com/AnthonyMastrean/chocolateypackages/049a54b5879eeef310cf0ce715c30887bec9ac96/public/icons/tinycc.png
> 
>Please provide an uninstall script (chocolateyUninstall.ps1). Chocolatey no longer completely removes the installation directory. But, it does track extracted files in a text file in the install directory (<package-name>Install.zip.txt). If you provide it this information, it can clean up properly.
> 
>     Uninstall-ChocolateyZipPackage -PackageName 'tinycc' -ZipFileName 'tinyccInstall.zip'

**Comment by gep13** [comment]
Done.

Can't think why you wouldn't have been able to moderate it :-(

Gary

**Comment by ferventcoder** [comment]
I have no idea why it would be running into issues. Maybe there is a need to clean up some browser cookies and stuff and give it another shot. I'm going to close this for now since the actual request was fixed. If you run into this again we should create another issue to address this.

**Comment by AnthonyMastrean** [comment]
I still cannot moderate tinycc and now add speq to the list.

https://chocolatey.org/packages/tinycc
https://chocolatey.org/packages/speq

I didn't get the error message this time, but I got some other strange behavior. I tried this several times. I enter my comments, choose a status, and click submit... 

 * Another package page was loaded (which was open in another tab)
 * I was returned to the package list
 * The same package page was reloaded without any of my changes saved

I logged off, cleared cookies, and restarted the browser. No luck, same behavior.
